feat: add pnpm

diff --git a/.github/workflows/deploy-frontend-monorepo.yml b/.github/workflows/deploy-frontend-monorepo.yml
--- a/.github/workflows/deploy-frontend-monorepo.yml
+++ b/.github/workflows/deploy-frontend-monorepo.yml
@@ -17,7 +17,7 @@ on:
         type: string
     secrets:
       ORG_PGP_TOKEN:
-        description: Org token for npm
+        description: Org token for pnpm
         required: true
       sentry_auth_token:
         required: false
@@ -35,6 +35,11 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
+      - name: Install pnpm
+        uses: pnpm/action-setup@v4
+        with:
+          version: 9
 
       - id: get-env
         run: |
@@ -122,13 +127,13 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: ${{ steps.config.outputs.version }}
+          cache: 'pnpm'
 
-      - name: Sets npm and yarn config
+      - name: Sets pnpm config
         run: |
-          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.ORG_PGP_TOKEN }}
-          npm config set @orfium:registry https://npm.pkg.github.com
-          npm config set always-auth true || echo "This fails for versions > 18.13"
-          yarn config set @orfium:registry https://npm.pkg.github.com
+          pnpm config set //npm.pkg.github.com/:_authToken ${{ secrets.ORG_PGP_TOKEN }}
+          pnpm config set @orfium:registry https://npm.pkg.github.com
+          pnpm config set always-auth true || echo "This fails for versions > 18.13"
 
       - name: Setup env, install dependencies, and build app
         run: |
@@ -138,8 +143,8 @@ jobs:
               source ${{ inputs.app-directory-name }}/environments/common.env
           fi
           source ${{ inputs.app-directory-name }}/environments/${{ inputs.target-environment }}.env
-          yarn install
-          yarn build --filter=./${{ inputs.app-directory-name }}
+          pnpm install
+          pnpm build --filter=./${{ inputs.app-directory-name }}
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4.0.2
@@ -207,7 +212,7 @@ jobs:
           echo "INVALIDATION_ID is $INVALIDATION_ID"
 
       - name: Generate sourcemaps
-        run: yarn build:sentry --filter=./${{ inputs.app-directory-name }}
+        run: pnpm build:sentry --filter=./${{ inputs.app-directory-name }}
 
       - name: Set deployment env
         id: set-environment
