feat: try catch block on branches loop

diff --git a/.github/workflows/fe-combine-dependabot-prs.yml b/.github/workflows/fe-combine-dependabot-prs.yml
--- a/.github/workflows/fe-combine-dependabot-prs.yml
+++ b/.github/workflows/fe-combine-dependabot-prs.yml
@@ -104,10 +104,22 @@ jobs:
           git config pull.rebase false
           git config user.name github-actions
           git config user.email github-actions@github.com
-
+          
+          echo $sourcebranches
+          
           git branch $COMBINE_BRANCH_NAME $basebranch
           git checkout $COMBINE_BRANCH_NAME
-          git pull origin $sourcebranches --no-edit
+          
+          for sourceBranch in $sourcebranches
+          do
+            {
+              git pull origin $sourceBranch --no-edit
+            } || {
+              git merge --abort
+              echo "Failed branch is ${{sourceBranch}}"
+            }
+          done
+          
           git push origin $COMBINE_BRANCH_NAME
       # Creates a PR with the new combined branch
       - uses: actions/github-script@v6
